### ISSUE TITLE
Will it has a tui?

### ISSUE THREAD

**Issue by lucasjinreal** [araekiel/jot#15]
Will it has a tui?

**Comment by lucasjinreal** [comment]
If so, I bet it gonna replace with Obsidian.

**Comment by shashwatah** [comment]
Sorry, but no. 
Even though I started off this project writing a TUI (with [tui-rs](https://github.com/fdehau/tui-rs), trying to replicate [glow](https://github.com/charmbracelet/glow)'s look), I soon realized this won't achieve what I wanted, so I instead switched to a CLI app. 
This can be used in conjunction with Obsidian, if you are interested in that.
